title = "Gitleaks Config"

[extend]
useDefault = true

[[rules]]
description = "PAN Card"
id = "pan-card"
regex = '''([A-Za-z]{3}[ABCFGHJLPTabcfghjlpt][A-Za-z]{1}\d{4}[A-Za-z]{1})'''
secretGroup = 1

[allowlist]
  description = "Allowlist for test PAN cards"
  regexes = [
    '''^ZZZ[A-Z]{2}[0-9]{4}[A-Z]$'''
  ]
