title = "Gitleaks Config"

[extend]
useDefault = true

[[rules]]
description = "PAN Card"
id = "pan-card"
regex = '''([^A-Za-z0-9]|^)([A-Z]{3}[ABCFGHJLPT][A-Z]{1}[0-9]{4}[A-Z])([^A-Za-z0-9]|$)'''
secretGroup = 1
