name: Update Gitleaks Configuration

on:
  schedule:
    # Runs every day at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml
        pip install -r requirements.txt

    - name: Merge Gitleaks Configurations
      run: |
        # Use Python script or any other method to fetch and merge configurations
        python merge-gitleaks.py

    - name: Commit and Push if Changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update Gitleaks configuration via GitHub Action"
        git push
